​task_batches = {
"Project Management Tools and Templates": [
"Decision Log",
"Task Plan",
"Gaps List",
"Individual Work List",
"Data Migration Tracking Plan",
"Communications Plan",
"Phase Sign-Off Process",
"Risk Analysis/Mitigation Plan",
"Risk Analysis/Mitigation Plan",
"Gaps List",
"Steering Committee Presentation Templates",
"Data Migration Tracking Plan",
"Testing Strategy Template",
"Data Migration Tracking Plan",
"Steering Committee Presentation Templates",
"EDI Tracking",
"Individual Work List",
"Phase Sign-Off Process",
"Issue Management Plan and Issues List",
"Task Plan",
"Decision Log",
"WRICEF Tracking Plan",
"Decision Log",
"Communications Plan",
"Risk Analysis/Mitigation Plan"
],
"Quality Reviews": [
"Deliverable Reviews",
"Q-Gate Reviews",
],
"Data Migration Approach": [
"Data Mapping",
"Extract and Transform",
"Cleanse",
"Pre-validation",
"Correct",
"Harmonize",
"Cleanse",
"Extract and Transform",
"Complexity Assessment",
"Data Mapping",
"Cleanse",
"Post-validation",
"Complexity Assessment",
"Confirm and Plan",
"Pre-validation",
"Development",
"Data Mapping",
],
"Embedded Analytics": [
"Identification of potential customizations relative to Fiori reports.",
"Customization of ten 10| Fiori-based reports.",
"Identification of potential customizations relative to Fiori reports.",
"Workshops across the various functional areas to help identify out-of-box Embedded Analytics Fiori-based reports to be leveraged.",
"Customization of ten 10| Fiori-based reports.",
"Workshops across the various functional areas to help identify out-of-box Embedded Analytics Fiori-based reports to be leveraged.",
"Customization of ten 10| Fiori-based reports.",
"Workshops across the various functional areas to help identify out-of-box Embedded Analytics Fiori-based reports to be leveraged."
],
"Analytics: S/4HANA Data Integration to Existing MS Azure based Landscape": [
"Identify S/4 sources table/views to for use with the current Data Liberator/SLT based integration with the current MS Azure based target database.",
"Data to be replicated in same manner as ECC",
"Data to be replicated in same manner as ECC",
"Identify S/4 sources table/views to for use with the current Data Liberator/SLT based integration with the current MS Azure based target database.",
"Identify S/4 sources table/views to for use with the current Data Liberator/SLT based integration with the current MS Azure based target database.",
"CDS view modification to support replication process as needed."
],
"SAP Analytics Cloud SAC| Implementation w/ or w/out Datasphere DSP|": [
"Formal system/integration testing",
"12 twelve| developed stories Dashboard/Visualizations/Excel|",
"SAC Cloud Connector/DPA set-up as applicable|",
"SAC Cloud Connector/DPA set-up as applicable|",
"Security configuration",
"Formal system/integration testing",
"Formal system/integration testing",
"Establish required source system integration",
"Formal system/integration testing",
"SAC Cloud Connector/DPA set-up as applicable|",
"Security configuration",
"Security configuration"
],
"Technical Development of Workflows, Reports, Interfaces, Conversions, Enhancements, Forms WRICEF| and Electronic Data Interface EDI|": [
"Unit Test",
"Unit Test",
"Final Acceptance Test",
"Functional specification - Voice of Customer",
"Final Acceptance Test",
"Functional specification - Voice of Customer",
"Agreement on scope for WRICEF object",
"Final Acceptance Test",
"Final Acceptance Test",
"Agreement on scope for WRICEF object",
"Agreement on scope for WRICEF object",
"Final Acceptance Test",
"Functional specification - Voice of Customer",
"Agreement on scope for WRICEF object",
"Testing",
"Agreement on scope for WRICEF object",
"Unit Test"
],
"PREP": [
"Project Kickoff and Onboarding",
"Contract Signature",
"Phase Closure and Signoff Phase Deliverables",
"System Provisioning and Solution Activation",
"Project Plan",
"Contract Signature",
"Project Organization Structure",
"Self Enablement",
"Self Enablement",
"Project Kickoff and Onboarding",
"Project Portal",
"Phase Closure and Signoff Phase Deliverables",
"Project Initiation",
"Project Kickoff and Onboarding",
"Contract Signature",
"Project Initiation"
],
"EXPLORE": [
"User Access and Security Strategy",
"Phase Initiation",
"Fit To Standard Workshop",
"SAP Development and Test Environment Provisioning",
"Organization Structure Workshop and Data Education",
"High Level Value Chain Scenarios",
"Phase Closure and Signoff Phase Deliverables",
"Phase Closure and Signoff Phase Deliverables",
"Data Mapping Documents",
"Phase Initiation",
"User Access and Security Strategy",
"Solution Readout",
"High Level Value Chain Scenarios",
"Fit to Standard Workshops",
"Solution Readout",
"Fit To Standard Workshop",
"Data Mapping Documents",
"Q-Gate review of Deploy Phase",
"Project Team Enablement"
],
"REALIZE": [
"Test Data Preparation for Integration Test Cycle 1",
"Quality Management Master Inspection Method",
"Functional Configuration",
"EDI030 - 870 Order Status",
"Unit and String Testing",
"INT009 - Order Stimulate Order Change API",
"Request the S/4HANA Cloud Test System",
"INT037 - Stock",
"Sales Ops| 1F1-Debit Memo Processing",
"Manufacturing| BJN-Rework Processing - Stock-Manufactured Material",
"Manufacturing| 2V0-SAP Fiori Analytical Apps for Quality Management",
"Manage the Development of Enablement Content",
"Sales Ops| 2LN-Basic Available-to-Promise Processing",
"Manufacturing| 3LO-Change Manufacturing  Bill of Material for Production",
"EDI005 – 947 Warehouse  Inventory Adjustment Advice",
"MM Scheduling Agreements"
],
"DEPLOY": [
"Go-Live Authorization",
"Setup Operations Control Center",
"Training and OCM",
"Business Cutover Plan",
"Go live authorization form signed by client",
"Define Phase Closure & Sign-Off Process & Criteria.",
"Production Cutover – Business and Legacy Systems",
"Business Cutover Plan",
"Establish Operations Readiness criteria.",
"Setup Operations Control Center",
"Data Validation",
"System performance testing",
"BPOs assist end users in change",
"Phase Initiation",
"Go live authorization form signed by client",
"Data Loads into SAP",
"Production Cutover – SAP System"
],
"RUN": [
"Project Closure and Signoff Project Deliverables",
"Project Closure and Signoff Project Deliverables",
"Q-Gate review of Run Phase",
"Establish Hypercare operations.",
"Hypercare completion",
"Issues Resolution",
"Project Closure and Signoff Project Deliverables",
"Month-End Close Process",
"Project Stage I Closure and Signoff Project Phase Deliverables",
"Issues Resolution",
"Hypercare completion",
"Hypercare complete",
"Issues Resolution",
"Deploy User Experience Management Tools.",
"Month-End Close Process"
]
}
