name: Build and deploy Python app + Worker to Azure Web App - activate-plus-sow-analyzer
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
 
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
     
      - name: Install dependencies
        run: pip install -r requirements.txt
       
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
 
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: |
            .
            !venv/
            !worker/   # exclude worker, separate job will handle it
 
  deploy-webapp:
    runs-on: ubuntu-latest
    needs: build-webapp
 
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
 
      - name: 'Deploy FastAPI WebApp'
        uses: azure/webapps-deploy@v3
        id: deploy-webapp
        with:
          app-name: 'activate-plus-sow-analyzer'
 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
 
  build-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Prepare worker package
        run: |
          cd worker
          chmod +x run.sh
          zip -r ../worker.zip *
 
      - name: Upload worker artifact
        uses: actions/upload-artifact@v4
        with:
          name: worker
          path: worker.zip
 
  deploy-worker:
    runs-on: ubuntu-latest
    needs: build-worker
 
    steps:
      - name: Download worker artifact
        uses: actions/download-artifact@v4
        with:
          name: worker
 
      - name: Deploy Worker WebJob
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'activate-plus-sow-analyzer'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: worker.zip
